### ISSUE TITLE
panic: runtime error: index out of range [-1] when retrieving workflow task

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/go-workflows#200]
```
=== RUN   Test_RedisBackend/CreateWorkflowInstance_SameInstanceIDErrors
panic: runtime error: index out of range [-1]

goroutine 45 [running]:
github.com/cschleiden/go-workflows/backend/redis.(*redisBackend).GetWorkflowTask(0xc000317aa0, {0xcf3be8, 0xc0002bff20})
	/home/runner/work/go-workflows/go-workflows/backend/redis/workflow.go:110 +0xfc5
github.com/cschleiden/go-workflows/internal/worker.(*WorkflowWorker).poll(0xc000273730, {0xcf3b78, 0xc00007b9c0}, 0x6fc23ac00)
	/home/runner/work/go-workflows/go-workflows/internal/worker/workflow.go:238 +0xf1
github.com/cschleiden/go-workflows/internal/worker.(*WorkflowWorker).runPoll(0xc000273730, {0xcf3b78, 0xc00007b9c0})
	/home/runner/work/go-workflows/go-workflows/internal/worker/workflow.go:92 +0x110
created by github.com/cschleiden/go-workflows/internal/worker.(*WorkflowWorker).Start
	/home/runner/work/go-workflows/go-workflows/internal/worker/workflow.go:64 +0x87
FAIL	github.com/cschleiden/go-workflows/backend/redis	1.2[62](https://github.com/cschleiden/go-workflows/actions/runs/4898582673/jobs/8747858451#step:5:63)s
FAIL
```

**Comment by cschleiden** [comment]
Another instance: https://github.com/cschleiden/go-workflows/actions/runs/6252748593/job/16976679041?pr=242

**Comment by cschleiden** [comment]
This should be fixed 🤞 A previous test failure left a worker running that conflicted with subsequent unit tests
