### ISSUE TITLE
Broken samples with sqlite

### ISSUE THREAD

**Issue by lyuboxa** [cschleiden/go-workflows#258]
Hello,

Seems like the new driver upgrade for sqlite, broke bunch of the samples.
In this case, it may be wise to set `SetMaxOpenConns(1)` on all sqlite backends, and/or split usage between rw/r connections. 

```
klou=; go run ./simple/... --backend sqlite
2023/10/20 15:49:54 ERROR error while polling for workflow task error="locking workflow task: database is locked (5) (SQLITE_BUSY)"
2023/10/20 15:49:54 ERROR error while polling for workflow task error="locking workflow task: database is locked (5) (SQLITE_BUSY)"
2023/10/20 15:49:55 ERROR error while polling for workflow task error="locking workflow task: database is locked (5) (SQLITE_BUSY)"
2023/10/20 15:49:56 ERROR error while polling for workflow task error="locking workflow task: database is locked (5) (SQLITE_BUSY)"
2023/10/20 15:49:56 ERROR error while polling for workflow task error="locking workflow task: database is locked (5) (SQLITE_BUSY)"
2023/10/20 15:49:57 ERROR error while polling for workflow task error="locking workflow task: database is locked (5) (SQLITE_BUSY)"
2023/10/20 15:49:57 ERROR could not complete workflow task error="unlocking workflow instance: database is locked (5) (SQLITE_BUSY)"
panic: could not complete workflow task

goroutine 111 [running]:
github.com/cschleiden/go-workflows/internal/worker.(*WorkflowWorker).handle(0x140001322a0, {0x10109b270, 0x101540b60}, 0x140002ce360)
	/Users/lyubo/src/go-workflows/internal/worker/workflow.go:182 +0x5dc
github.com/cschleiden/go-workflows/internal/worker.(*WorkflowWorker).runDispatcher.func1()
	/Users/lyubo/src/go-workflows/internal/worker/workflow.go:127 +0x70
created by github.com/cschleiden/go-workflows/internal/worker.(*WorkflowWorker).runDispatcher in goroutine 28
	/Users/lyubo/src/go-workflows/internal/worker/workflow.go:122 +0xa4
exit status 2
```

**Comment by cschleiden** [comment]
👀  it still works locally for me here. Did you try with latest main?

**Comment by lyuboxa** [comment]
I just did and couldn't reproduce, I may have been on another branch. Sorry about this! Works as expected.

**Comment by cschleiden** [comment]
Perfect, thanks for checking
